# Generated by Django 3.0.3 on 2020-06-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('similarity', models.FloatField(max_length=15)),
                ('faceId', models.CharField(max_length=50)),
                ('width', models.FloatField(max_length=15)),
                ('height', models.FloatField(max_length=15)),
                ('left', models.FloatField(max_length=15)),
                ('top', models.FloatField(max_length=15)),
                ('imageId', models.CharField(max_length=50)),
                ('confidence', models.FloatField(max_length=15)),
            ],
        ),
    ]
