# Generated by Django 3.0.3 on 2020-06-16 15:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api_aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='face',
            managers=[
                ('face_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='face',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='face',
            name='faceId',
        ),
        migrations.RemoveField(
            model_name='face',
            name='height',
        ),
        migrations.RemoveField(
            model_name='face',
            name='imageId',
        ),
        migrations.RemoveField(
            model_name='face',
            name='left',
        ),
        migrations.RemoveField(
            model_name='face',
            name='name',
        ),
        migrations.RemoveField(
            model_name='face',
            name='similarity',
        ),
        migrations.RemoveField(
            model_name='face',
            name='top',
        ),
        migrations.RemoveField(
            model_name='face',
            name='width',
        ),
    ]
