# Generated by Django 3.0.3 on 2020-06-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_aws', '0002_auto_20200616_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='faceId',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='height',
            field=models.FloatField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='imageId',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='left',
            field=models.FloatField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='similarity',
            field=models.FloatField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='top',
            field=models.FloatField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='face',
            name='width',
            field=models.FloatField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
