# Generated by Django 3.0.3 on 2020-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_aws', '0003_auto_20200616_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='height',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='face',
            name='left',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='face',
            name='similarity',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='face',
            name='top',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='face',
            name='width',
            field=models.FloatField(max_length=30),
        ),
    ]
